spring.application.name=find-translator-backend
spring.threads.virtual.enabled=true

find-translator.websocket.allowed-origins=http://localhost:5500,http://127.0.0.1:5500,http://localhost:4200
find-translator.matching.find-active-time=PT10M
find-translator.matching.offer-active-time=PT5M
find-translator.matching.max-find-sessions=100
find-translator.matching.max-offer-sessions=5000
